Microondas/Controllers/MicroondasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Microondas.Domain.ViewModels;
using ctrl = Microondas.Domain.Controller;
using Microsoft.AspNet.SignalR;
using Microondas.Hubs;
using System.Threading;
using System.Threading.Tasks;
using System.Net;

namespace Microondas.Controllers
{
    public class MicroondasController : Controller
    {
        JavaScriptSerializer _serialize = new JavaScriptSerializer();
        ctrl.MicoondasControler _microondasCtrl= new ctrl.MicoondasControler();
        ctrl.ProgramaController _programaCtrl = new ctrl.ProgramaController();
        // GET: Microondas
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProgramasPadrao()
        {
            ViewBag.padroes = _programaCtrl.ObterProgramasPadrao();
            if (Session["programas"]  != null)
            {
                string teste = (string)Session["programas"];
                ViewBag.customizados = _serialize.Deserialize<List<ProgramaViewModel>>(teste);
            }
            return PartialView();
        }
        [HttpPost]
        public ActionResult Ligar(MicroondasViewModel microondas)
        {
            if (ModelState.IsValid)
            {
                microondas.ServerPath = Server.MapPath("~/Alimentos");
                var gotResult = false;
                ActionResult result = null;
                var cancellation = new CancellationTokenSource();
                CancellationToken ct = cancellation.Token;
                Task.Factory.StartNew(() =>
                {
                    result = Json(_microondasCtrl.Ligar(microondas, NotificarUsuario));
                    gotResult = true;
                }, ct);
                while (!gotResult)
                {
                    if (!Response.IsClientConnected)
                    {
                        cancellation.Cancel();
                        _microondasCtrl.Desligar();
                        return result;
                    }
                    Thread.Sleep(100);
                }
                return result;
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
        }
        [HttpGet]
        public ActionResult Pesquisar(string term)
        {
            List<ProgramaViewModel> customizados = new List<ProgramaViewModel>();
            List<ProgramaViewModel> padroes = _programaCtrl.ObterProgramasPadrao();
            if (Session["programas"] != null)
            {
                customizados = _serialize.Deserialize<List<ProgramaViewModel>>((String)Session["programas"]);
            }
            if (term != "")
            {
                ViewBag.customizados = customizados.Where(c => c.Nome.Contains(term) || c.TipoAlimento.Contains(term)).ToList();
                ViewBag.padroes = padroes.Where(c => c.Nome.Contains(term) || c.TipoAlimento.Contains(term)).ToList();
            }
            else
            {
                ViewBag.customizados = customizados;
                ViewBag.padroes = padroes;
            }
            return PartialView("ProgramasPadrao");
        }
        private bool NotificarUsuario(int tempoPercorrido, string alimento)
        {
            ProgressHub.SendMessage(tempoPercorrido, alimento);
            return true;
        }
    }
}

Microondas/Controllers/ProgramaController.cs
using Microondas.Domain.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Microondas.Controllers
{
    public class ProgramaController : Controller
    {
        JavaScriptSerializer _serialize = new JavaScriptSerializer();
        // GET: Programa
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProgramaViewModel programa)
        {
            if (ModelState.IsValid)
            {
                List<ProgramaViewModel> programas = new List<ProgramaViewModel>();
                programas.Add(programa);
                Session["programas"] = _serialize.Serialize(programas);
                return RedirectToAction("Index", "Microondas");
            }
            else
            {
                return View();
            }
        }
    }
}

Microondas/Views/Microondas/Index.cshtml
@model Microondas.Domain.ViewModels.MicroondasViewModel
@{
    ViewBag.Title = "Index";
}
<div class="page-header">
    <h1>Configurar Micoondas</h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                @using (Html.BeginForm("Ligar", "Microondas", FormMethod.Post, new { @id = "micoondasForm", role = "form" }))
                {
                    @Html.AntiForgeryToken();
                    HtmlHelper.UnobtrusiveJavaScriptEnabled = false;
                    <div class="form-group">
                        @Html.LabelFor(m => m.Alimento)
                        @Html.TextBoxFor(m => m.Alimento, new { @class = "form-control" })
                    </div>
                    <h3>Configurações</h3>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Tempo)
                        @Html.TextBoxFor(m => m.Tempo, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Potencia)
                        @Html.TextBoxFor(m => m.Potencia, new { @class = "form-control" })
                    </div>
                    <button id="btnLigar" type="button" class="btn btn-primary">Ligar</button>
                    <button id="btnInicioRapido" type="button" class="btn btn-primary">inicio Rápido</button>
                    <button id="btnPausar" data-action="pausar" type="button" class="btn btn-warning">Pausar</button>
                    <button id="btnCancelar" type="button" class="btn btn-danger">Cancelar</button>
                }
            </div>
            <div id="alimentoAquecido">

            </div>
        </div>
        <div class="col-md-6">
            <div class="programas-content">
                <div class="form-inline form-group">
                    <div class="form-group">
                        <input id="inputPerqTerm" type="text" class="form-control" />
                    </div>
                    <button type="button" id="btnPerquisar" class="btn btn-info">Pesquisar</button>
                    @Html.ActionLink("Novo Programa", "Create", "Programa", null, new { @class = "btn btn-success" })
                </div>
                @Html.Action("ProgramasPadrao")
            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/form-validations-custom-layout.js"></script>
    <script src="~/Scripts/messages.js"></script>
    <script src="~/Scripts/Micoondas/index.js"></script>
}

Microondas/Views/Microondas/ProgramasPadrao.cshtml
@using Microondas.Domain.ViewModels

@PrintLista(ViewBag.padroes, "Programas")

@if (ViewBag.customizados != null)
{
    @PrintLista(ViewBag.customizados, "Programas Customizados")
}
@helper PrintLista(List<ProgramaViewModel> lista, string title)
    {
        <div id="contentTable">
            <h3>@title</h3>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>Nome</td>
                        <td>Instruções</td>
                        <td>TipoAlimento</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (ProgramaViewModel p in lista)
                    {
                        <tr>
                            <td>@p.Nome</td>
                            <td>@p.Instrucoes</td>
                            <td>@p.TipoAlimento</td>
                            <td>
                                <button class="btn btn-info iniciarPrograma"
                                        data-alimento="@p.TipoAlimento"
                                        data-id="@p.Id"
                                        data-caractere="@p.Caractere"
                                        data-potencia="@p.Potencia"
                                        data-tempo="@p.Tempo">
                                    Iniciar
                                </button>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
}

Microondas/Views/Programa/Create.cshtml
@model Microondas.Domain.ViewModels.ProgramaViewModel
@{
    ViewBag.Title = "Create";
}
<div class="page-header">
    <h1>Programa</h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="mb-3">
                @using (Html.BeginForm("Create", "Programa", FormMethod.Post, new { @id = "micoondasForm", role = "form" }))
                {
                    @Html.AntiForgeryToken();
                    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
                    <div class="form-group">
                        @Html.LabelFor(m => m.Nome)
                        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Nome, "", new { @class = "text-danger " })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Instrucoes)
                        @Html.TextBoxFor(m => m.Instrucoes, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Instrucoes, "", new { @class = "text-danger " })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Tempo)
                        @Html.TextBoxFor(m => m.Tempo, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Tempo, "", new { @class = "text-danger " })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Potencia)
                        @Html.TextBoxFor(m => m.Potencia, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Potencia, "", new { @class = "text-danger " })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.TipoAlimento)
                        @Html.TextBoxFor(m => m.TipoAlimento, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.TipoAlimento, "", new { @class = "text-danger " })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Caractere)
                        @Html.TextBoxFor(m => m.Caractere, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Caractere, "", new { @class = "text-danger " })
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                }
            </div>
        </div>
    </div>
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Microondas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("css", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Microondas", "Index", "Microondas", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>